# Development Docker Compose with live code updates
# Run with: docker-compose -f docker-compose.dev.yml up

services:
  fastfoto-scanner-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastfoto-date-scanner-dev
    restart: unless-stopped
    ports:
      - "${FLASK_PORT:-5000}:5000"
    volumes:
      # Mount source code for live updates
      - ./src:/app/src
      - ./static:/app/static
      - ./templates:/app/templates
      
      # Mount data directory for persistent storage  
      - ./data/photos/unprocessed:/app/data/photos/unprocessed
      - ./data/photos/processed:/app/data/photos/processed
      - ./data/db:/app/data/db
      - ./data/thumbs:/app/data/thumbs
      
      # Mount requirements for live updates
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
    environment:
      # Development-specific settings
      - FLASK_DEBUG=true
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Pagination Settings
      - PHOTOS_PER_PAGE=${PHOTOS_PER_PAGE:-100}
      
      # Directory Paths (Docker paths)
      - PHOTOS_UNPROCESSED_DIR=/app/data/photos/unprocessed
      - PHOTOS_PROCESSED_DIR=/app/data/photos/processed
      
      # Similarity Analysis Settings  
      - SIMILARITY_EPS=${SIMILARITY_EPS:-0.3}
      - SIMILARITY_MIN_SAMPLES=${SIMILARITY_MIN_SAMPLES:-2}
      
      # Flask Settings
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-secret-key}
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      
      # Disable scheduled tasks in development
      - SCAN_INTERVAL_HOURS=0
    working_dir: /app
    command: python src/app.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"